# Generated by Django 4.0.3 on 2022-03-26 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id_car', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('plate', models.CharField(max_length=8)),
                ('time', models.CharField(max_length=255)),
                ('paid', models.BooleanField()),
                ('left', models.BooleanField()),
                ('create_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
