# Generated by Django 4.0.3 on 2022-03-28 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_cars_id_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='left',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cars',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
