# Generated by Django 4.0.3 on 2022-03-29 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_cars_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='time',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
